### ISSUE TITLE
Source plugin should bundle generated sources

### ISSUE THREAD

**Issue by dmlloyd** [jboss/jboss-parent-pom#25]
Otherwise it's impossible to make sense of exceptions, or problems in generated source.

**Comment by ctomc** [comment]
this should be fixed in 17 i just released, but i don't really like how it works as it is supported by compiler-plugin which also exposes source path to few undesired places like checkstyle.
As result i wont close this quite yet

**Comment by ctomc** [comment]
should be fixed
