### ISSUE TITLE
Maven sources plugin 3.3.0 Issues

### ISSUE THREAD

**Issue by emmartins** [jboss/jboss-parent-pom#253]
The Maven Sources plugin has serious bugs ([MSOURCES-140](https://issues.apache.org/jira/browse/MSOURCES-140), [MSOURCES-143](https://issues.apache.org/jira/browse/MSOURCES-143), [MSOURCES-121](https://issues.apache.org/jira/browse/MSOURCES-121) which causes popular builds to fail, specially MSOURCES-140.

Do not upgrade the Maven Sources plugin past 3.2.1 until there is a release version which includes the fix for at least MSOURCES-140.

**Comment by dmlloyd** [comment]
We'll keep this open until the upstream problems are resolved.
