### ISSUE TITLE
Remove timestamps from build configuration

### ISSUE THREAD

**Issue by pgier** [jboss/jboss-parent-pom#26]
Adding timestamps to the various archive files jars, zips, bundles, etc. makes it impossible to reproduce exact binaries from one build to the next.  External metadata can be used for tracking time and date of a release without affecting build reproducibility.

**Comment by pgier** [comment]
Just to give some background on this, we've discussed it a bit within productization, but didn't really come to a definitive answer on whether we should include timestamps in our builds.  So I'm looking for feedback on this, such as if there are strong use cases for timestamps.

Some other open source projects are also working on trying to achieve byte for byte build reproducibility (https://wiki.debian.org/ReproducibleBuilds)

**Comment by ctomc** [comment]
I don't mind the change. Not really sure if we use timestamp for anything. at least in wildfly/eap and its related projects

**Comment by ctomc** [comment]
fixed as part of #27
