### ISSUE TITLE
Enforcer plugin  3.0.0-M2 regression

### ISSUE THREAD

**Issue by mareknovotny** [jboss/jboss-parent-pom#54]
Enforcer has a regression see at https://issues.apache.org/jira/browse/MENFORCER-306, so every project which uses parent with plugin definitions and have enforcer rule `org.apache.maven.plugins.enforcer.RequirePluginVersions` will experience false alarm on not defined plugin versions.

https://github.com/jboss/jboss-parent-pom/commit/5e0b974f4088d67dfe14d36eaeea99d94ac76dc5#commitcomment-31061581

**Comment by dmlloyd** [comment]
Looks like this is fixed upstream: https://issues.apache.org/jira/browse/MENFORCER-306?focusedCommentId=16776364&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16776364

I guess we'll keep watch for a release?

**Comment by mareknovotny** [comment]
great, hopefully the release of 3.0.0 will be soon
