### ISSUE TITLE
Upgrade to maven-release-plugin 3.0.0-M1

### ISSUE THREAD

**Issue by ppalaga** [jboss/jboss-parent-pom#89]
This mainly motivated by https://issues.apache.org/jira/browse/MRELEASE-1029 which adds automatic updates of the `project.build.outputTimestamp` property during release. See also https://maven.apache.org/guides/mini/guide-reproducible-builds.html

**Comment by Swastik-123** [comment]
Please assign me this issue ,I would like to solved it.

**Comment by dmlloyd** [comment]
This is complete.
