### ISSUE TITLE
Can we remove org.codehaus.mojo:license-maven-plugin from jboss parent?

### ISSUE THREAD

**Issue by bxf12315** [jboss/jboss-parent-pom#97]
Our team's parent pom is jboss parent, now I want to use com.mycila:license-maven-plugin,
but it conflicts to org.codehaus.mojo:license-maven-plugin. Maybe move the license plugin into child project is better.
Thanks

**Comment by ctomc** [comment]
How does it conflict with com.mycila:license-maven-plugin? Here you only have managed version defined, it is not defined to be included in any life cycle of the project.
so beyond managing version of plugin, there is noting here that would clash with config in your project.

**Comment by darranl** [comment]
The main use of this pom is as the parent pom for the various JBoss / WildFly projects to configure the common requirements of these projects such as where our releases are published to and the other common plugins our projects we need.

If we were to remove something this wouldn't be about a single child project there are many child projects that would loose the definition.

As an Apache licensed pom I don't know if instead you may be better to fork it to make use of the common configuration that is useful to you and then adapt as needed for your own projects.

**Comment by bxf12315** [comment]
> How does it conflict with com.mycila:license-maven-plugin? Here you only have managed version defined, it is not defined to be included in any life cycle of the project.
> so beyond managing version of plugin, there is noting here that would clash with config in your project.
you are right, org.codehaus.mojo:license-maven-plugin just definite in pluginManagement. I can solve it.
@ctomc @darranl 
Thanks a lot!
